version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys: 
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run Tests
          command: yarn test --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_artifacts:
          path: "reports/junit/js-test-results.xml"
          prefix: tests
      - store_test_results:
          path: "reports/junit/js-test-results.xml"
        