version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10.16.0

aliases:
  restore_cache: &restore_cache
    restore_cache:
      name: Restore Npm Package Cache
      keys:
        - yarn-cache-netlify-{{ checksum "yarn.lock" }}

  install_node_modules: &install_node_modules
    run:
      name: Install dependencies
      command: yarn install

  save_cache: &save_cache
    save_cache:
      name: Save NPM package cache
      key: yarn-cache-netlify-{{ checksum "yarn.lock" }}
      paths:
        - ./node_modules
  install_netlify: &install_netlify
    run:
      name: Install netlify-cli
      command: sudo npm install -g --silent netlify-cli

jobs:
  test:
    executor: node
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *save_cache
      - run:
          name: Test
          command: yarn test

  build-staging:
    executor: node
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *save_cache
      - run:
          name: Build
          command: |
            export REACT_APP_ENV=staging
            export REACT_APP_API_KEY=http://staging.google.com
            yarn build
      - persist_to_workspace:
          root: .
          paths: .
   
  build-prod:
    executor: node
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *save_cache
      - run:
          name: Build
          command: |
            export REACT_APP_ENV=production
            export REACT_APP_API_KEY=http://google.com
            yarn build
      - persist_to_workspace:
          root: .
          paths: production

  deploy-staging:
    executor: node
    steps:
      - attach_workspace:
          at: ./
      - <<: *install_netlify
      - run:
          name: Deploy to Staging
          command: netlify deploy --dir=./build --site=${STAGING_SITE_ID} --prod --message "${CIRCLE_USERNAME}:${CIRCLE_SHA1}"

  deploy-prod:
    executor: node
    steps:
      - attach_workspace:
          at: ./
      - <<: *install_netlify
      - run: 
          name: Deploy to Production
          command: netlify deploy --dir=./build --site=${PROD_SITE_ID} --prod --message "${CIRCLE_USERNAME}:${CIRCLE_SHA1}"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - gh-pages
      - build-staging:
          requires:
            - test
          filters:
            branches:
              only:
                - /release.*/
                - /hotfix.*/
                - develop
      - deploy-staging:
          requires:
            - build-staging
          filters:
            branches:
              only:
                - /release.*/
                - /hotfix.*/
                - develop
      - build-prod:
          requires:
            - test
          filters:
            branches:
              only: 
                - master
      - deploy-prod:
          requires:
            - build-prod
          filters:
            branches:
              only: 
                - master
